# Generated by Django 4.1.7 on 2023-02-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=200)),
                ("release_date", models.DateField()),
                ("category", models.CharField(max_length=200)),
                ("played", models.BooleanField()),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
