# Generated by Django 4.1.7 on 2023-02-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_alter_game_played"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="slug",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
    ]
